#!/bin/zsh

#nvim picker function
items=("default" "LazyVim" "nvchad")
config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Nvim Config → " --height=~50% --layout=reverse --border --exit-0)
if [[ -z $config ]]; then
  echo "Nothing selected"
  return 0
elif [[ $config == "default" ]]; then
  config=""
fi
NVIM_APPNAME=$config nvim $@

bindkey -s ^e 'nvims\n'
