-- Generated by HyprMod

-- Settings
hl.config({
    animations = {
        enabled = false,
    },
    general = {
        allow_tearing = true,
        border_size = 1,
        snap = {
            enabled = false,
        },
    },
})
