-- Managed by Omarchy Keybind Manager. Do not edit this file.

-- This file is regenerated by omarchy-keybind-manager.
-- Every managed key is explicitly unbound first so it cleanly overrides Omarchy defaults.

hl.unbind("SUPER + SHIFT + K")
o.bind("SUPER + SHIFT + K", "Keybind Manager", "uwsm-app -- sh -lc " .. o.shell_quote("omarchy-launch-tui --app-id=org.omarchy.keybind-manager omarchy-keybind-manager"))

hl.unbind("SUPER + ALT + SPACE")
o.bind("SUPER + ALT + SPACE", "Omarchy menu", "uwsm-app -- sh -lc " .. o.shell_quote("omarchy menu"))

