-- Managed by Omarchy Keybind Manager. Do not edit this file.

-- This file is regenerated by omarchy-keybind-manager.
-- Every managed key is explicitly unbound first so it cleanly overrides Omarchy defaults.

hl.unbind("SUPER + SHIFT + K")
o.bind("SUPER + SHIFT + K", "Keybind Manager", "uwsm-app -- sh -lc " .. o.shell_quote("omarchy-launch-tui --app-id=org.omarchy.keybind-manager omarchy-keybind-manager"))

hl.unbind("SUPER + ALT + SPACE")
o.bind("SUPER + ALT + SPACE", "Omarchy menu", "uwsm-app -- sh -lc " .. o.shell_quote("omarchy menu"))

hl.unbind("SUPER + SHIFT + O")
o.bind("SUPER + SHIFT + O", "OCR", "uwsm-app -- sh -lc " .. o.shell_quote("omarchy-capture-text"))

hl.unbind("SUPER + CTRL + S")
o.bind("SUPER + CTRL + S", "screenshot", "uwsm-app -- sh -lc " .. o.shell_quote("omarchy-capture-screenshot"))

hl.unbind("SUPER + E")
o.bind("SUPER + E", "Explain Code", "uwsm-app -- sh -lc " .. o.shell_quote("sh -c 'wtype -M ctrl -k c -m ctrl && sleep 0.3 && vicinae \"vicinae://launch/@tariq/gemini-chat/ask?fallbackText=%2Fexplain-code\"'"))

hl.unbind("SUPER + SHIFT + E")
o.bind("SUPER + SHIFT + E", "gmail", "uwsm-app -- sh -lc " .. o.shell_quote("omarchy-launch-webapp https://gmail.google.com"))

