return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    -- your configuration comes here
    --     -- or leave it empty to use the default settings
    --         -- refer to the configuration section below
    --
  },
  keys = {
    {
      "<leader>?",
      function()
        require("which-key").show({ global = false })
      end,
      desc = "Buffer Local Keymaps (which-key)",
    },
  },

  config = function()
    local wk = require("which-key")

    wk.add({
      { "<leader>to", "<cmd>TodoComments<CR>",                                        desc = "Todo Comments" },
      { "<leader>tt", "<cmd>TodoList<CR>",                                            desc = "Todo List" },
      { "<leader>Ls", "<cmd>ToggleDiagnostics<CR>",                                   desc = "ToggleDiagnostics" },
      { "<leader>db", "<cmd>lua require('dap').toggle_breakpoint()<cr>",              desc = "Toggle Breakpoint" },
      { "<leader>dc", "<cmd>lua require('dap').continue()<cr>",                       desc = "Continue" },
      { "<leader>dn", "<cmd>lua require('dap').step_over()<cr>",                      desc = "Step Over" },
      { "<leader>di", "<cmd>lua require('dap').step_into()<cr>",                      desc = "Step Into" },
      { "<leader>do", "<cmd>lua require('dap').step_out()<cr>",                       desc = "Step Out" },
      { "<leader>dr", "<cmd>lua require('dap').repl.open()<cr>",                      desc = "Repl" },
      { "<leader>du", "<cmd>lua require('dapui').toggle()<cr>",                       desc = "Dap UI" },
      { "<leader>dq", "<cmd>lua require('dap').terminate()<cr>",                      desc = "Terminate" },
      { "<leader>ll", "<cmd>Lazy load all<cr>",                                       desc = "Load plugins" },
      { "<leader>s",  "<cmd>w<cr>",                                                   desc = "Save" },
      { "<leader>q",  "<cmd>q<cr>",                                                   desc = "Quit" },
      { "<leader>Q",  "<cmd>qa!<cr>",                                                 desc = "Quit all" },
      { "<leader>e",  "<cmd>Oil --float<cr>",                                         desc = "Oil Nvim" },
      { "<leader>c",  "<cmd>bd<cr>",                                                  desc = "Close buffer" },
      -- { "<leader>C",  "<cmd>bufdo bd!<cr>",                                           desc = "Close all buffers" },
      { "<leader>x",  "<cmd>BufferLinePickClose<cr>",                                 desc = "Pick Close buffer" },
      -- { "<leader>r",  "<cmd>w<cr>:sp | terminal python3 %<CR>",                       desc = "run python in a horizontal split" },
      { "<leader>r",  "<cmd>w<cr>:Cook<CR>",                                          desc = "run code in a floating window" },
      -- { "<leader>j",  "<cmd>w<cr>:sp | terminal node %<CR>",                          desc = "run JS file in a horizontal split" },
      -- { "<leader>k",  "<cmd>w<cr>:sp | terminal cargo run % <CR>",                    desc = "Compile TS file" },
      { "<leader>h",  "<cmd>Alpha<CR>",                                               desc = "show dashboard" },
      { "<leader>gg", "<cmd>LazyGit<CR>",                                             desc = "open lazygit" },
      { "<leader>z",  "<cmd>lua require('telescope').extensions.notify.notify()<CR>", desc = "show notifications" },
      { "<leader>n",  "<cmd>enew<CR>",                                                desc = "new buffer" },
      -- { '"',          "<cmd>Telescope registers<CR>",                                 desc = "registers" },
      { "<leader>ww", "<C-w>w",                                                       desc = "focus next window" },
      { "<leader>ws", "<C-w>s",                                                       desc = "split window below" },
      { "<leader>wv", "<C-w>v",                                                       desc = "split window right" },
      { "<leader>wq", "<C-w>q",                                                       desc = "close window" },
      { "<leader>pm", "<cmd>Mason<CR>",                                               desc = "Mason" },
      { "<leader>pM", "<cmd>MasonUpdate<CR>",                                         desc = "MasonUpdate" },
      { "<leader>pa", "<cmd>Lazy update<CR>",                                         desc = "Update plugins" },
      { "<leader>ps", "<cmd>Lazy sync<CR>",                                           desc = "Sync plugins" },
      { "<leader>pU", "<cmd>Lazy check<CR>",                                          desc = "Check Update" },
      { "<leader>pp", "<cmd>MCPHub<CR>",                                              desc = "MCPHub" },
      { "<leader>fa", "<cmd>Config <CR>",                                             desc = "Nvim config files" },
      { "<leader>fo", "<cmd>Telescope oldfiles<CR>",                                  desc = "open old files" },
      { "<leader>fe", "<cmd>Telescope treesitter<CR>",                                desc = "Treesitter Symbols" },
      { "<leader>fc", "<cmd>Telescope commands<CR>",                                  desc = "commands" },
      { "<leader>fk", "<cmd>Telescope keymaps<CR>",                                   desc = "keymaps" },
      { "<leader>fh", "<cmd>Telescope help_tags<CR>",                                 desc = "help tags" },
      { "<leader>fd", "<cmd>Telescope fd <CR>",                                       desc = "find files" },
      { "<leader>fg", "<cmd>Telescope live_grep<CR>",                                 desc = "live grep" },
      { "<leader>fb", "<cmd>Telescope buffers<CR>",                                   desc = "buffers" },
      { "<leader>fw", "<cmd>Telescope grep_string<CR>",                               desc = "grep string" },
      { "<leader>f/", "<cmd>Telescope current_buffer_fuzzy_find<CR>",                 desc = "fuzzy find in current buffer" },
      { "<leader>ff", "<cmd>Telescope find_files<CR>",                                desc = "find files" },
      { "<leader>fr", "<cmd>Telescope lsp_references<CR>",                            desc = "references" },
      { "<leader>fm", "<cmd>Telescope marks<CR>",                                     desc = "marks" },
      { "<leader>ft", "<cmd>Telescope colorscheme<CR>",                               desc = "themes" },
      { "<leader>fT", "<cmd>TodoTelescope<CR>",                                       desc = "Find TODOs" },
      { "<leader>fz", "<cmd>Telescope zoxide list<CR>",                               desc = "zoxide" },
      { "<leader>lr", "<cmd>lua vim.lsp.buf.rename()<CR>",                            desc = "rename" },
      { "<leader>la", "<cmd>lua vim.lsp.buf.code_action()<CR>",                       desc = "code action" },
      { "<leader>ld", "<cmd>lua vim.diagnostic.open_float()<CR>",                     desc = "diagnostic" },
      { "<leader>lf", "<cmd>lua vim.lsp.buf.format({ async = true })<CR>",            desc = "format" },
      { "<leader>lt", "<cmd>lua vim.lsp.buf.type_definition()<CR>",                   desc = "type definition" },
      { "<leader>ls", "<cmd>lua vim.lsp.buf.signature_help()<CR>",                    desc = "signature help" },
      { "<leader>lw", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>",              desc = "add workspace folder" },
      { "<leader>li", "<cmd>LspInfo<CR>",                                             desc = "lsp info" },
      { "<leader>k",  "<cmd>Noice dismiss<CR>",                                       desc = "dismiss notifications" },
      { "<leader>u",  "<cmd>UndotreeToggle<CR>",                                      desc = "undotree" },
      { "<leader>ic", "<cmd>Fitten toggle_chat<CR>",                                  desc = "Fitten chat [i]" },
      { "<leader>is", "<cmd>Fitten start_chat<CR>",                                   desc = "Start chat [s]" },
      { "<leader>th", "<cmd>split term://zsh<CR>",                                    desc = "horizontal terminal" },
      { "<leader>tv", "<cmd>vsplit term://zsh<CR>",                                   desc = "vertical terminal" },
      { "<leader>tf", "<cmd>FloatermToggle <CR>",                                     desc = "floating terminal" },
      { "<leader>D",  "<cmd>w<cr>:sp |terminal g++ % -o %:r && ./%:r<CR>",            desc = "compile and run c++" },
      { "<leader>m",  "<cmd>DBUIToggle<CR>",                                          desc = "Deploy DBUI" },
      { "<leader>y",  "<cmd>InspectTree<CR>",                                         desc = "Inspect tree" },
      { "<leader>oo", "<cmd>TSJToggle<CR>",                                           desc = "Toggle TSJ" },
      { "<leader>os", "<cmd>ObsidianQuickSwitch<CR>",                                 desc = "Obsidian quick search" },
      { "<leader>og", "<cmd>ObsidianSearch<CR>",                                      desc = "Obsidian grep search" },
      { "<leader>on", "<cmd>ObsidianNewFromTemplate<CR>",                             desc = "Obsidian new file" },
      { "<leader>ot", "<cmd>ObsidianTags<CR>",                                        desc = "Obsidian tags" },
      { "<leader>ol", "<cmd>ObsidianLink<CR>",                                        desc = "Create Link" },
      { "<leader>of", "<cmd>ObsidianFollowLink<CR>",                                  desc = "Follow Link" },
      { "<leader>or", "<cmd>ObsidianRename<CR>",                                      desc = "Rename current buffer" },
      { "<leader>vp", "<cmd>MarkdownPreviewToggle<CR>",                               desc = "Markdown Preview" },
      { "<leader>vs", "<cmd>MarkdownPreviewStop<CR>",                                 desc = "Markdown Stop" }
    })
  end
}
